os:
- linux
- windows

language: go

go:
- 1.x

go_import_path: github.com/GoogleCloudPlatform/ops-agent

before_install:
- go get github.com/mattn/goveralls

script:
- go test -mod=mod ./...
- $GOPATH/bin/goveralls -service=travis-ci
