FROM ubuntu:focal AS mingw

RUN set -x; apt-get update && \
    DEBIAN_FRONTEND=noniteractive apt-get -y install golang git \
    autoconf libtool libltdl-dev \
    build-essential cmake bison flex file \
    devscripts cdbs \
    mingw-w64

RUN go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest; \
    go install github.com/google/addlicense@latest; \
    go install github.com/pavius/impi/cmd/impi@latest; \
    go install github.com/google/googet/v2/goopack@latest;

COPY . /work
WORKDIR /work
RUN patch -d ./submodules/fluent-bit/ -p 1 <./pkg/goo/mingw64-support.patch || true
RUN ./pkg/goo/build.sh

FROM scratch
COPY --from=mingw /tmp/google-cloud-ops-agent.tgz /google-cloud-ops-agent-windows-ltsc2019.tgz
COPY --from=mingw /google-cloud-ops-agent*.goo /
