# escape=`

ARG WINDOWS_VERSION=ltsc2022

#
# Builder Image - Windows Server Core
#
FROM mcr.microsoft.com/windows/servercore:$WINDOWS_VERSION as base

#
# Basic setup
#
RUN setx /M PATH "%PATH%;C:\Go\bin"

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

RUN Write-Host ('Creating folders'); `
    New-Item -Type Directory -Path /local; `
    New-Item -Type Directory -Path /work/out/bin; `
    New-Item -Type Directory -Path /work/out/config;

WORKDIR /local

#
# Install Golang
#
ADD https://go.dev/dl/go1.26.4.windows-amd64.msi /local/go1.26.4.windows-amd64.msi

RUN Start-Process msiexec.exe `
    -ArgumentList '/i C:\local\go1.26.4.windows-amd64.msi ', '/quiet ', `
    '/norestart ', 'ALLUSERS=1,INSTALLDIR=C:\Go' -NoNewWindow -Wait;

#
# Install Go build tools
#

# Run these in a directory with a go.mod file so that "go get" doesn't need
# a working Git installation.
WORKDIR /goget

# @latest has an issue with path separators, so pin to an older version for now.
# https://github.com/google/googet/issues/83#issuecomment-2536975624
RUN go install github.com/google/googet/v2/goopack@v2.18.4;

ENV GO_BIN_PATH="C:\Go\bin"




###############################################################################
# Build OT collector
###############################################################################

COPY submodules/opentelemetry-operations-collector /work/submodules/opentelemetry-operations-collector

WORKDIR /work/submodules/opentelemetry-operations-collector/otelopscol

RUN & ./build.ps1 -outDir /work/out/bin

###############################################################################
# Config generator/service installer
###############################################################################

WORKDIR /work

COPY . /work

ARG WINDOWS_VERSION
ARG BUILD_DISTRO=windows-$WINDOWS_VERSION
RUN Get-Content VERSION | Where-Object length | ForEach-Object { Invoke-Expression "`$env:$_" }; `
    go build -o bin/google-cloud-ops-agent.exe -ldflags \"-X github.com/GoogleCloudPlatform/ops-agent/internal/version.BuildDistro=$env:BUILD_DISTRO -X github.com/GoogleCloudPlatform/ops-agent/internal/version.Version=$env:PKG_VERSION\" ./cmd/ops_agent_windows; `
    Copy-Item -Path bin/google-cloud-ops-agent.exe -Destination /work/out/bin/; `
    Copy-Item -Path confgenerator/default-config.yaml -Destination /work/out/config/config.yaml;

###############################################################################



###############################################################################
# Build the Ops Agent UAP plugin
###############################################################################

WORKDIR /work

COPY . /work

ARG WINDOWS_VERSION
ARG BUILD_DISTRO=windows-$WINDOWS_VERSION
RUN Get-Content VERSION | Where-Object length | ForEach-Object { Invoke-Expression "`$env:$_" }; `
    go build -o bin/ops_agent.exe -ldflags \"-X github.com/GoogleCloudPlatform/ops-agent/internal/version.BuildDistro=$env:BUILD_DISTRO -X github.com/GoogleCloudPlatform/ops-agent/internal/version.Version=$env:PKG_VERSION\" ./cmd/ops_agent_uap_plugin; `
    Copy-Item -Path bin/ops_agent.exe -Destination /work/out/bin/; `
    $env:PKG_VERSION | Out-File -FilePath /work/out/bin/OPS_AGENT_VERSION -Encoding UTF8;

###############################################################################
# Packaging
###############################################################################

WORKDIR /work

COPY . /work

ARG PACKAGE="false"
# Always copy maint.ps1, even when not running as a presubmit.
RUN Copy-Item -Path .\pkg\goo\maint.ps1 -Destination /work/out/bin/;

RUN if ($env:PACKAGE -eq 'true') { `
      & .\pkg\goo\build.ps1 -DestDir /work/out; `
      ls /work/out; `
    }

###############################################################################
# Packaging for the Ops Agent Plugin
###############################################################################

WORKDIR /work

COPY . /work

RUN & .\pkg\plugin\build.ps1 -DestDir /work/out/bin;
