# escape=`

ARG WINDOWS_VERSION=ltsc2022

#
# Builder Image - Windows Server Core
#
FROM mcr.microsoft.com/windows/servercore:$WINDOWS_VERSION as base

#
# Basic setup
#
RUN setx /M PATH "%PATH%;C:\Go\bin"

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

RUN Write-Host ('Creating folders'); `
    New-Item -Type Directory -Path /local; `
    New-Item -Type Directory -Path /work/out/bin; `
    New-Item -Type Directory -Path /work/out/config;

###############################################################################
# Install build prerequisites
###############################################################################

WORKDIR /local

#
# Install Visual Studio Build Tools 2019 (MSVS_VERSION=16) / 2022 (MSVS_VERSION=17, requires WINDOWS_VERSION=ltsc2022)
# Based on https://github.com/fluent/fluent-bit/blob/v4.0.7/dockerfiles/Dockerfile.windows
#
ARG MSVS_VERSION="17"
ENV MSVS_BUILD_TOOLS_VERSION="$MSVS_VERSION" `
    MSVS_BUILD_TOOLS_DOWNLOAD_URL="https://aka.ms/vs" `
    MSVS_HOME="C:\BuildTools"

RUN $msvs_build_tools_dist_name=\"vs_buildtools.exe\"; `
    $msvs_build_tools_dist=\"${env:TMP}\${msvs_build_tools_dist_name}\"; `
    $msvs_build_tools_channel=\"C:\local\VisualStudio.chman\"; `
    $msvs_build_tools_dist_url=\"${env:MSVS_BUILD_TOOLS_DOWNLOAD_URL}/${env:MSVS_BUILD_TOOLS_VERSION}/release/${msvs_build_tools_dist_name}\"; `
    $msvs_build_tools_channel_url=\"${env:MSVS_BUILD_TOOLS_DOWNLOAD_URL}/${env:MSVS_BUILD_TOOLS_VERSION}/release/channel\"; `
    Write-Host \"Downloading Visual Studio Build Tools...\"; `
    Write-Host \"${msvs_build_tools_dist_url} -> ${msvs_build_tools_dist}\"; `
    Write-Host \"${msvs_build_tools_channel_url} -> ${msvs_build_tools_channel}\"; `
    Invoke-WebRequest -OutFile \"${msvs_build_tools_dist}\" \"${msvs_build_tools_dist_url}\"; `
    Invoke-WebRequest -OutFile \"${msvs_build_tools_channel}\" \"${msvs_build_tools_channel_url}\"; `
    Write-Host \"Installing Visual Studio Build Tools into ${env:MSVS_HOME}...\"; `
    Start-Process \"${msvs_build_tools_dist}\" `
      -ArgumentList '--quiet ', '--wait ', '--norestart ', '--nocache', `
      \"--installPath ${env:MSVS_HOME}\", `
      \"--channelUri ${msvs_build_tools_channel}\", `
      \"--installChannelUri ${msvs_build_tools_channel}\", `
      '--add Microsoft.VisualStudio.Workload.VCTools', `
      '--includeRecommended'  -NoNewWindow -Wait; `
    Remove-Item -Force \"${msvs_build_tools_dist}\"; `
    Remove-Item -Path \"${msvs_build_tools_channel}\" -Force;

#
# Install compatible CMake
#
ENV CMAKE_HOME="C:\cmake"
ARG CMAKE_VERSION="3.31.6"
ARG CMAKE_URL="https://github.com/Kitware/CMake/releases/download"

RUN if ([System.Version] \"${env:CMAKE_VERSION}\" -ge [System.Version] \"3.20.0\") { `
      $cmake_dist_base_name=\"cmake-${env:CMAKE_VERSION}-windows-x86_64\" `
    } else { `
      if ([System.Version] \"${env:CMAKE_VERSION}\" -ge [System.Version] \"3.6.0\") { `
        $cmake_dist_base_name=\"cmake-${env:CMAKE_VERSION}-win64-x64\" `
      } else { `
        $cmake_dist_base_name=\"cmake-${env:CMAKE_VERSION}-win32-x86\" `
      } `
    }; `
    $cmake_dist_name=\"${cmake_dist_base_name}.zip\"; `
    $cmake_dist=\"${env:TMP}\${cmake_dist_name}\"; `
    $cmake_download_url=\"${env:CMAKE_URL}/v${env:CMAKE_VERSION}/${cmake_dist_name}\"; `
    Write-Host \"Downloading CMake...\"; `
    Write-Host \"${cmake_download_url} -> ${cmake_dist}\"; `
    Invoke-WebRequest -OutFile \"${cmake_dist}\" \"${cmake_download_url}\"; `
    $cmake_temp_dir=\"${env:TMP}\${cmake_dist_base_name}\"; `
    Write-Host \"Extracting CMake...\"; `
    Write-Host \"${cmake_dist} -> ${cmake_temp_dir}\"; `
    Expand-Archive \"${cmake_dist}\" -Destination \"${env:TMP}\"; `
    Remove-Item -Force \"${cmake_dist}\"; `
    Write-Host \"Moving CMake...\"; `
    Write-Host \"${cmake_temp_dir} -> ${env:CMAKE_HOME}\"; `
    [System.IO.Directory]::Move(\"${cmake_temp_dir}\", \"${env:CMAKE_HOME}\"); `
    $env:PATH=\"${env:PATH};${env:CMAKE_HOME}\bin\"; `
    Write-Host \"Setting PATH...\"; `
    Write-Host \"${env:PATH}\"; `
    [Environment]::SetEnvironmentVariable(\"PATH\", \"${env:PATH}\", [EnvironmentVariableTarget]::Machine);

#
# Install WinFlexBison
#
ENV WIN_FLEX_BISON_VERSION="2.5.22" `
    WIN_FLEX_BISON_HOME="C:\WinFlexBison" `
    WIN_FLEX_BISON_DOWNLOAD_URL="https://github.com/lexxmark/winflexbison/releases/download"

RUN $win_flex_bison_dist_base_name=\"win_flex_bison-${env:WIN_FLEX_BISON_VERSION}\"; `
    $win_flex_bison_dist_name=\"${win_flex_bison_dist_base_name}.zip\"; `
    $win_flex_bison_dist=\"${env:TMP}\${win_flex_bison_dist_name}\"; `
    $win_flex_bison_url=\"${env:WIN_FLEX_BISON_DOWNLOAD_URL}/v${env:WIN_FLEX_BISON_VERSION}/${win_flex_bison_dist_name}\"; `
    Write-Host \"Downloading WinFlexBison...\"; `
    Write-Host \"${win_flex_bison_url} -> ${win_flex_bison_dist}\"; `
    Invoke-WebRequest -OutFile \"${win_flex_bison_dist}\" \"${win_flex_bison_url}\"; `
    Write-Host \"Extracting WinFlexBison...\"; `
    Write-Host \"${win_flex_bison_dist} -> ${env:WIN_FLEX_BISON_HOME}\"; `
    Expand-Archive \"${win_flex_bison_dist}\" -Destination \"${env:WIN_FLEX_BISON_HOME}\"; `
    Remove-Item -Force \"${win_flex_bison_dist}\"; `
    Write-Host \"Copying...\"; `
    Write-Host \"${env:WIN_FLEX_BISON_HOME}\win_bison.exe -> ${env:WIN_FLEX_BISON_HOME}\bison.exe\"; `
    Copy-Item -Path \"${env:WIN_FLEX_BISON_HOME}\win_bison.exe\" \"${env:WIN_FLEX_BISON_HOME}\bison.exe\"; `
    Write-Host \"Copying...\"; `
    Write-Host \"${env:WIN_FLEX_BISON_HOME}\win_flex.exe -> ${env:WIN_FLEX_BISON_HOME}\flex.exe\"; `
    Copy-Item -Path \"${env:WIN_FLEX_BISON_HOME}\win_flex.exe\" \"${env:WIN_FLEX_BISON_HOME}\flex.exe\"; `
    $env:PATH=\"${env:PATH};${env:WIN_FLEX_BISON_HOME}\"; `
    Write-Host \"Setting PATH...\"; `
    Write-Host \"${env:PATH}\"; `
    [Environment]::SetEnvironmentVariable(\"PATH\", \"${env:PATH}\", [EnvironmentVariableTarget]::Machine);

#
# Install VCPKG
#
# https://github.com/microsoft/vcpkg/blob/2024.12.16/scripts/bootstrap.ps1
ENV VCPKG_VERSION=2024.12.16 `
    VCPKG_DOWNLOAD_URL="https://github.com/microsoft/vcpkg/archive/refs/tags" `
    VCPKG_DISABLE_METRICS="ON" `
    VCPKG_ROOT=/dev/vcpkg

WORKDIR /dev

RUN $vcpkg_dist_base_name=\"vcpkg-${env:VCPKG_VERSION}\"; `
    $vcpkg_dist=\"${env:TMP}\${vcpkg_dist_base_name}.zip\"; `
    $vcpkg_url=\"${env:VCPKG_DOWNLOAD_URL}/${env:VCPKG_VERSION}.zip\"; `
    Write-Host \"Downloading vcpkg...\"; `
    Write-Host \"${vcpkg_url} -> ${vcpkg_dist}\"; `
    Invoke-WebRequest -OutFile \"${vcpkg_dist}\" \"${vcpkg_url}\"; `
    $vcpkg_temp_dir=\"${env:TMP}\${vcpkg_dist_base_name}\"; `
    Write-Host \"Extracting vcpkg...\"; `
    Write-Host \"${vcpkg_dist} -> ${vcpkg_temp_dir}\"; `
    Expand-Archive \"${vcpkg_dist}\" -Destination \"${env:TMP}\"; `
    Remove-Item -Force \"${vcpkg_dist}\"; `
    $vcpkg_home_dir=\"${env:VCPKG_ROOT}\" -replace \"/\", \"\\\"; `
    $vcpkg_home_dir=\"C:${vcpkg_home_dir}\"; `
    Write-Host \"Moving vcpkg...\"; `
    Write-Host \"${vcpkg_temp_dir} -> ${vcpkg_home_dir}\"; `
    [System.IO.Directory]::Move(\"${vcpkg_temp_dir}\", \"${vcpkg_home_dir}\"); `
    $env:PATH=\"${env:PATH};${vcpkg_home_dir}\"; `
    Write-Host \"Setting PATH...\"; `
    Write-Host \"${env:PATH}\"; `
    [Environment]::SetEnvironmentVariable(\"PATH\", \"${env:PATH}\", [EnvironmentVariableTarget]::Machine); `
    Write-Host \"Bootstrapping vcpkg...\"; `
    & \"${vcpkg_home_dir}\bootstrap-vcpkg.bat\";

# Ensure we only attempt to build release and static linking
ENV VCPKG_BUILD_TYPE=release `
    VCPKG_LIBRARY_LINKAGE=static

#
# Install OpenSSL and LibYAML
#
RUN vcpkg install --recurse openssl --triplet x64-windows-static; `
    vcpkg install --recurse libyaml --triplet x64-windows-static;

# Technique from https://github.com/StefanScherer/dockerfiles-windows/blob/master/mongo/3.6/Dockerfile
WORKDIR /work/out/bin/
RUN Copy-Item -Path C:\Windows\System32\msvcp140.dll -Destination /work/out/bin/; `
    Copy-Item -Path C:\Windows\System32\vccorlib140.dll -Destination /work/out/bin/; `
    Copy-Item -Path C:\Windows\System32\vcruntime140.dll -Destination /work/out/bin/;

#
# Install Golang
#
ADD https://go.dev/dl/go1.25.0.windows-amd64.msi /local/go1.25.0.windows-amd64.msi

RUN Start-Process msiexec.exe `
    -ArgumentList '/i C:\local\go1.25.0.windows-amd64.msi ', '/quiet ', `
    '/norestart ', 'ALLUSERS=1,INSTALLDIR=C:\Go' -NoNewWindow -Wait;

#
# Install Go build tools
#

# Run these in a directory with a go.mod file so that "go get" doesn't need
# a working Git installation.
WORKDIR /goget

# @latest has an issue with path separators, so pin to an older version for now.
# https://github.com/google/googet/issues/83#issuecomment-2536975624
RUN go install github.com/google/googet/v2/goopack@v2.18.4;

ENV GO_BIN_PATH="C:\Go\bin"




###############################################################################
# Build OT collector
###############################################################################

COPY submodules/opentelemetry-operations-collector /work/submodules/opentelemetry-operations-collector

WORKDIR /work/submodules/opentelemetry-operations-collector/otelopscol

RUN & ./build.ps1 -outDir /work/out/bin

###############################################################################
# Config generator/service installer
###############################################################################

WORKDIR /work

COPY . /work

ARG WINDOWS_VERSION
ARG BUILD_DISTRO=windows-$WINDOWS_VERSION
RUN Get-Content VERSION | Where-Object length | ForEach-Object { Invoke-Expression "`$env:$_" }; `
    go build -o bin/google-cloud-ops-agent.exe -ldflags \"-X github.com/GoogleCloudPlatform/ops-agent/internal/version.BuildDistro=$env:BUILD_DISTRO -X github.com/GoogleCloudPlatform/ops-agent/internal/version.Version=$env:PKG_VERSION\" ./cmd/ops_agent_windows; `
    Copy-Item -Path bin/google-cloud-ops-agent.exe -Destination /work/out/bin/; `
    Copy-Item -Path confgenerator/default-config.yaml -Destination /work/out/config/config.yaml;

###############################################################################



###############################################################################
# Build the Ops Agent UAP plugin
###############################################################################

WORKDIR /work

COPY . /work

ARG WINDOWS_VERSION
ARG BUILD_DISTRO=windows-$WINDOWS_VERSION
RUN Get-Content VERSION | Where-Object length | ForEach-Object { Invoke-Expression "`$env:$_" }; `
    go build -o bin/ops_agent.exe -ldflags \"-X github.com/GoogleCloudPlatform/ops-agent/internal/version.BuildDistro=$env:BUILD_DISTRO -X github.com/GoogleCloudPlatform/ops-agent/internal/version.Version=$env:PKG_VERSION\" ./cmd/ops_agent_uap_plugin; `
    Copy-Item -Path bin/ops_agent.exe -Destination /work/out/bin/; `
    $env:PKG_VERSION | Out-File -FilePath /work/out/bin/OPS_AGENT_VERSION -Encoding UTF8;

###############################################################################
# Packaging
###############################################################################

WORKDIR /work

COPY . /work

ARG PACKAGE="false"
# Always copy maint.ps1, even when not running as a presubmit.
RUN Copy-Item -Path .\pkg\goo\maint.ps1 -Destination /work/out/bin/;

RUN if ($env:PACKAGE -eq 'true') { `
      & .\pkg\goo\build.ps1 -DestDir /work/out; `
      ls /work/out; `
    }

###############################################################################
# Packaging for the Ops Agent Plugin
###############################################################################

WORKDIR /work

COPY . /work

RUN & .\pkg\plugin\build.ps1 -DestDir /work/out/bin;
