# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file was generated by dockerfiles/compile.go
# To re-generate, run from the repository root: go run ./dockerfiles

# Build as DOCKER_BUILDKIT=1 docker build -o /tmp/out .
# or DOCKER_BUILDKIT=1 docker build -o /tmp/out . --target=bullseye
# Generated tarball(s) will end up in /tmp/out


ARG CMAKE_VERSION=3.25.2
ARG GO_VERSION=1.26.4
ARG USE_PREBUILT=false
ARG TARGETARCH

# Manually prepare a recent enough version of CMake.
# This should be used on platforms where the default package manager
# does not provide a recent enough version (we require >= 3.12).
FROM alpine:latest AS cmake-amd64-recent
ARG CMAKE_VERSION

ENV hash=4d98de8d605da676e71a889dd94f80c76abb377fade2f21e3510e62ece1e1ada
ADD https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}-linux-x86_64.sh \
    /cmake.sh

FROM alpine:latest AS cmake-arm64-recent
ARG CMAKE_VERSION

ENV hash=73a35cab2174a3eb8f35083d55c80871185dc3808f3dae3558cd5fbdb29a4614
ADD https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}-linux-aarch64.sh \
    /cmake.sh

FROM cmake-${TARGETARCH}-recent AS cmake-install-recent
RUN set -xe; (echo "$hash  /cmake.sh" | sha256sum -c)



# ======================================
# Shared Go Binaries Build - Architecture Specific Bases
# ======================================

# AMD64 Base (SLES 12)
FROM opensuse/archive:42.3 AS go-builder-base-amd64
RUN set -x; \
    # The 'OSS Update' repo signature is no longer valid, so verify the checksum instead.
    zypper --no-gpg-check refresh 'OSS Update' && \
    (echo '6dd0b89202b19dae873434c5f2ba01164205071581fc02365712be801e304b3b /var/cache/zypp/raw/OSS Update/repodata/repomd.xml' | sha256sum --check) && \
    zypper -n install git systemd autoconf automake libtool libcurl-devel libopenssl-devel gcc8 gcc8-c++ zlib-devel expect systemd-devel unzip zip make curl && \
    # Remove expired root certificate.
    mv /var/lib/ca-certificates/pem/DST_Root_CA_X3.pem /etc/pki/trust/blacklist/ && \
    update-ca-certificates && \
    zypper -n update && \
    # Set newer GCC as default with priority 1
    update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 1 \
        --slave /usr/bin/g++ g++ /usr/bin/g++-8 && \
    update-alternatives --set gcc /usr/bin/gcc-8

# ARM64 Base (SLES 15)
FROM opensuse/leap:15.1 AS go-builder-base-arm64
RUN set -x; \
    zypper -n refresh && \
    zypper -n update && \
    zypper -n install git systemd autoconf automake libtool libcurl-devel libopenssl-devel gcc gcc-c++ zlib-devel rpm-build expect systemd-devel systemd-rpm-macros unzip zip make curl

# Selector
ARG TARGETARCH
FROM go-builder-base-${TARGETARCH} AS go-builder-base

# Common Compile Stage
FROM go-builder-base AS go-false
SHELL ["/bin/bash", "-c"]

# Install golang
ARG TARGETARCH
ARG GO_VERSION
ADD https://go.dev/dl/go${GO_VERSION}.linux-${TARGETARCH}.tar.gz /tmp/go${GO_VERSION}.tar.gz
RUN set -xe; \
    tar -xf /tmp/go${GO_VERSION}.tar.gz -C /usr/local
ENV PATH="${PATH}:/usr/local/go/bin"

WORKDIR /work

# 1. Download dependencies for the main repository
COPY go.mod go.sum ./
RUN go mod download

# 2. Download dependencies for the OTEL submodule
COPY ./submodules/opentelemetry-operations-collector/go.mod ./submodules/opentelemetry-operations-collector/go.sum submodules/opentelemetry-operations-collector/
RUN cd submodules/opentelemetry-operations-collector && go mod download

# Copy full source code
COPY . /work

# 3. Build otelopscol (CGO enabled)
RUN \
    unset OTEL_TRACES_EXPORTER && \
    unset OTEL_EXPORTER_OTLP_TRACES_ENDPOINT && \
    unset OTEL_EXPORTER_OTLP_TRACES_PROTOCOL && \
    ./builds/otel.sh /work/cache/

# 4. Build ops-agent-engine (CGO disabled)
RUN . VERSION && \
    BUILD_INFO_IMPORT_PATH="github.com/GoogleCloudPlatform/ops-agent/internal/version" && \
    BUILD_X1="-X ${BUILD_INFO_IMPORT_PATH}.BuildDistro=sles12" && \
    BUILD_X2="-X ${BUILD_INFO_IMPORT_PATH}.Version=${PKG_VERSION}" && \
    LD_FLAGS="-s -w ${BUILD_X1} ${BUILD_X2}" && \
    CGO_ENABLED=0 go build -buildvcs=false -o "/work/google_cloud_ops_agent_engine" \
      -ldflags "${LD_FLAGS}" \
      github.com/GoogleCloudPlatform/ops-agent/cmd/google_cloud_ops_agent_engine

# 5. Build ops_agent plugin helper (CGO disabled)
RUN ./builds/ops_agent_plugin.sh /work/plugin-cache/


# Stage to export prebuilt binaries to host
FROM scratch AS go-compile-export
COPY --from=go-false /work/google_cloud_ops_agent_engine /google_cloud_ops_agent_engine
COPY --from=go-false /work/cache /cache
COPY --from=go-false /work/plugin-cache /plugin-cache


# Stage to import prebuilt binaries from host
FROM scratch AS go-true
COPY ./built-binaries/google_cloud_ops_agent_engine /work/google_cloud_ops_agent_engine
COPY ./built-binaries/cache /work/cache
COPY ./built-binaries/plugin-cache /work/plugin-cache


# Final builder selector
FROM go-${USE_PREBUILT} AS go-build




# ======================================
# Build Ops Agent for centos-8
# ======================================

FROM rockylinux:8 AS centos8-build-base

RUN set -x; yum -y update && \
		dnf -y install 'dnf-command(config-manager)' && \
		yum config-manager --set-enabled powertools && \
		yum -y install systemd \
		file systemd-devel rpm-build systemd-rpm-macros \
		expect rpm-sign zip pkgconfig

SHELL ["/bin/bash", "-c"]



FROM centos8-build-base AS centos8-build-systemd
WORKDIR /work
COPY ./systemd systemd
COPY ./builds/systemd.sh .
RUN ./systemd.sh /work/cache/




FROM centos8-build-base AS centos8-build
WORKDIR /work
COPY . /work

# Copy the pre-compiled Go binaries from the shared build stage
COPY --from=go-build /work/google_cloud_ops_agent_engine /work/google_cloud_ops_agent_engine
COPY --from=go-build /work/cache /work/cache

COPY ./confgenerator/default-config.yaml /work/cache/etc/google-cloud-ops-agent/config.yaml

COPY --from=centos8-build-systemd /work/cache /work/cache

RUN ./pkg/rpm/build.sh

# Copy prebuilt plugin files to cache before packaging the plugin
COPY --from=go-build /work/plugin-cache /work/cache

RUN ./pkg/plugin/build.sh /work/cache centos8


FROM scratch AS centos8
COPY --from=centos8-build /tmp/google-cloud-ops-agent.tgz /google-cloud-ops-agent-centos-8.tgz
COPY --from=centos8-build /google-cloud-ops-agent*.rpm /
COPY --from=centos8-build /google-cloud-ops-agent-plugin*.tar.gz /

# ======================================
# Build Ops Agent for rockylinux-9
# ======================================

FROM rockylinux:9 AS rockylinux9-build-base

RUN set -x; dnf -y update && \
		dnf -y install 'dnf-command(config-manager)' && \
		dnf config-manager --set-enabled crb && \
		dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm && \
		dnf -y install systemd \
		file systemd-devel rpm-build systemd-rpm-macros \
		expect rpm-sign zip pkgconfig

SHELL ["/bin/bash", "-c"]



FROM rockylinux9-build-base AS rockylinux9-build-systemd
WORKDIR /work
COPY ./systemd systemd
COPY ./builds/systemd.sh .
RUN ./systemd.sh /work/cache/




FROM rockylinux9-build-base AS rockylinux9-build
WORKDIR /work
COPY . /work

# Copy the pre-compiled Go binaries from the shared build stage
COPY --from=go-build /work/google_cloud_ops_agent_engine /work/google_cloud_ops_agent_engine
COPY --from=go-build /work/cache /work/cache

COPY ./confgenerator/default-config.yaml /work/cache/etc/google-cloud-ops-agent/config.yaml

COPY --from=rockylinux9-build-systemd /work/cache /work/cache

RUN ./pkg/rpm/build.sh

# Copy prebuilt plugin files to cache before packaging the plugin
COPY --from=go-build /work/plugin-cache /work/cache

RUN ./pkg/plugin/build.sh /work/cache rockylinux9


FROM scratch AS rockylinux9
COPY --from=rockylinux9-build /tmp/google-cloud-ops-agent.tgz /google-cloud-ops-agent-rockylinux-9.tgz
COPY --from=rockylinux9-build /google-cloud-ops-agent*.rpm /
COPY --from=rockylinux9-build /google-cloud-ops-agent-plugin*.tar.gz /

# ======================================
# Build Ops Agent for rockylinux-10
# ======================================

FROM rockylinux/rockylinux:10 AS rockylinux10-build-base

RUN set -x; dnf -y update && \
		dnf -y install 'dnf-command(config-manager)' && \
		dnf config-manager --set-enabled crb && \
		dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-10.noarch.rpm && \
		dnf -y install systemd \
		file systemd-devel rpm-build systemd-rpm-macros \
		expect rpm-sign zip pkgconfig

SHELL ["/bin/bash", "-c"]



FROM rockylinux10-build-base AS rockylinux10-build-systemd
WORKDIR /work
COPY ./systemd systemd
COPY ./builds/systemd.sh .
RUN ./systemd.sh /work/cache/




FROM rockylinux10-build-base AS rockylinux10-build
WORKDIR /work
COPY . /work

# Copy the pre-compiled Go binaries from the shared build stage
COPY --from=go-build /work/google_cloud_ops_agent_engine /work/google_cloud_ops_agent_engine
COPY --from=go-build /work/cache /work/cache

COPY ./confgenerator/default-config.yaml /work/cache/etc/google-cloud-ops-agent/config.yaml

COPY --from=rockylinux10-build-systemd /work/cache /work/cache

RUN ./pkg/rpm/build.sh

# Copy prebuilt plugin files to cache before packaging the plugin
COPY --from=go-build /work/plugin-cache /work/cache

RUN ./pkg/plugin/build.sh /work/cache rockylinux10


FROM scratch AS rockylinux10
COPY --from=rockylinux10-build /tmp/google-cloud-ops-agent.tgz /google-cloud-ops-agent-rockylinux-10.tgz
COPY --from=rockylinux10-build /google-cloud-ops-agent*.rpm /
COPY --from=rockylinux10-build /google-cloud-ops-agent-plugin*.tar.gz /

# ======================================
# Build Ops Agent for debian-bookworm
# ======================================

FROM debian:bookworm AS bookworm-build-base

RUN set -x; apt-get update && \
		DEBIAN_FRONTEND=noninteractive apt-get -y install systemd \
		file libsystemd-dev \
		devscripts cdbs pkg-config zip

SHELL ["/bin/bash", "-c"]



FROM bookworm-build-base AS bookworm-build-systemd
WORKDIR /work
COPY ./systemd systemd
COPY ./builds/systemd.sh .
RUN ./systemd.sh /work/cache/




FROM bookworm-build-base AS bookworm-build
WORKDIR /work
COPY . /work

# Copy the pre-compiled Go binaries from the shared build stage
COPY --from=go-build /work/google_cloud_ops_agent_engine /work/google_cloud_ops_agent_engine
COPY --from=go-build /work/cache /work/cache

COPY ./confgenerator/default-config.yaml /work/cache/etc/google-cloud-ops-agent/config.yaml

COPY --from=bookworm-build-systemd /work/cache /work/cache

RUN ./pkg/deb/build.sh

# Copy prebuilt plugin files to cache before packaging the plugin
COPY --from=go-build /work/plugin-cache /work/cache

RUN ./pkg/plugin/build.sh /work/cache bookworm


FROM scratch AS bookworm
COPY --from=bookworm-build /tmp/google-cloud-ops-agent.tgz /google-cloud-ops-agent-debian-bookworm.tgz
COPY --from=bookworm-build /google-cloud-ops-agent*.deb /
COPY --from=bookworm-build /google-cloud-ops-agent-plugin*.tar.gz /

# ======================================
# Build Ops Agent for debian-bullseye
# ======================================

FROM debian:bullseye AS bullseye-build-base

RUN set -x; apt-get update && \
		DEBIAN_FRONTEND=noninteractive apt-get -y install systemd \
		file libsystemd-dev \
		devscripts cdbs pkg-config zip

SHELL ["/bin/bash", "-c"]



FROM bullseye-build-base AS bullseye-build-systemd
WORKDIR /work
COPY ./systemd systemd
COPY ./builds/systemd.sh .
RUN ./systemd.sh /work/cache/




FROM bullseye-build-base AS bullseye-build
WORKDIR /work
COPY . /work

# Copy the pre-compiled Go binaries from the shared build stage
COPY --from=go-build /work/google_cloud_ops_agent_engine /work/google_cloud_ops_agent_engine
COPY --from=go-build /work/cache /work/cache

COPY ./confgenerator/default-config.yaml /work/cache/etc/google-cloud-ops-agent/config.yaml

COPY --from=bullseye-build-systemd /work/cache /work/cache

RUN ./pkg/deb/build.sh

# Copy prebuilt plugin files to cache before packaging the plugin
COPY --from=go-build /work/plugin-cache /work/cache

RUN ./pkg/plugin/build.sh /work/cache bullseye


FROM scratch AS bullseye
COPY --from=bullseye-build /tmp/google-cloud-ops-agent.tgz /google-cloud-ops-agent-debian-bullseye.tgz
COPY --from=bullseye-build /google-cloud-ops-agent*.deb /
COPY --from=bullseye-build /google-cloud-ops-agent-plugin*.tar.gz /

# ======================================
# Build Ops Agent for debian-trixie
# ======================================

FROM debian:trixie AS trixie-build-base

RUN set -x; apt-get update && \
		DEBIAN_FRONTEND=noninteractive apt-get -y install systemd \
		file systemd-dev libsystemd-dev \
		devscripts cdbs pkg-config zip

SHELL ["/bin/bash", "-c"]



FROM trixie-build-base AS trixie-build-systemd
WORKDIR /work
COPY ./systemd systemd
COPY ./builds/systemd.sh .
RUN ./systemd.sh /work/cache/




FROM trixie-build-base AS trixie-build
WORKDIR /work
COPY . /work

# Copy the pre-compiled Go binaries from the shared build stage
COPY --from=go-build /work/google_cloud_ops_agent_engine /work/google_cloud_ops_agent_engine
COPY --from=go-build /work/cache /work/cache

COPY ./confgenerator/default-config.yaml /work/cache/etc/google-cloud-ops-agent/config.yaml

COPY --from=trixie-build-systemd /work/cache /work/cache

RUN ./pkg/deb/build.sh

# Copy prebuilt plugin files to cache before packaging the plugin
COPY --from=go-build /work/plugin-cache /work/cache

RUN ./pkg/plugin/build.sh /work/cache trixie


FROM scratch AS trixie
COPY --from=trixie-build /tmp/google-cloud-ops-agent.tgz /google-cloud-ops-agent-debian-trixie.tgz
COPY --from=trixie-build /google-cloud-ops-agent*.deb /
COPY --from=trixie-build /google-cloud-ops-agent-plugin*.tar.gz /

# ======================================
# Build Ops Agent for sles-12
# ======================================

FROM opensuse/archive:42.3 AS sles12-build-base

RUN set -x; \
		# The 'OSS Update' repo signature is no longer valid, so verify the checksum instead.
		zypper --no-gpg-check refresh 'OSS Update' && \
		(echo '6dd0b89202b19dae873434c5f2ba01164205071581fc02365712be801e304b3b /var/cache/zypp/raw/OSS Update/repodata/repomd.xml' | sha256sum --check) && \
		zypper -n install systemd rpm-build expect systemd-devel systemd-rpm-macros unzip zip pkgconfig && \
		# Remove expired root certificate.
		mv /var/lib/ca-certificates/pem/DST_Root_CA_X3.pem /etc/pki/trust/blacklist/ && \
		update-ca-certificates && \
		zypper -n update && \
		# Allow fluent-bit to find systemd
		ln -fs /usr/lib/systemd /lib/systemd

SHELL ["/bin/bash", "-c"]



FROM sles12-build-base AS sles12-build-systemd
WORKDIR /work
COPY ./systemd systemd
COPY ./builds/systemd.sh .
RUN ./systemd.sh /work/cache/




FROM sles12-build-base AS sles12-build
WORKDIR /work
COPY . /work

# Copy the pre-compiled Go binaries from the shared build stage
COPY --from=go-build /work/google_cloud_ops_agent_engine /work/google_cloud_ops_agent_engine
COPY --from=go-build /work/cache /work/cache

COPY ./confgenerator/default-config.yaml /work/cache/etc/google-cloud-ops-agent/config.yaml

COPY --from=sles12-build-systemd /work/cache /work/cache

RUN ./pkg/rpm/build.sh

# Copy prebuilt plugin files to cache before packaging the plugin
COPY --from=go-build /work/plugin-cache /work/cache

RUN ./pkg/plugin/build.sh /work/cache sles12


FROM scratch AS sles12
COPY --from=sles12-build /tmp/google-cloud-ops-agent.tgz /google-cloud-ops-agent-sles-12.tgz
COPY --from=sles12-build /google-cloud-ops-agent*.rpm /
COPY --from=sles12-build /google-cloud-ops-agent-plugin*.tar.gz /

# ======================================
# Build Ops Agent for sles-15
# ======================================

FROM opensuse/leap:15.1 AS sles15-build-base

RUN set -x; zypper -n refresh && \
		zypper -n update && \
		zypper -n install systemd rpm-build expect systemd-devel systemd-rpm-macros unzip zip pkgconfig
# Allow fluent-bit to find systemd
RUN ln -fs /usr/lib/systemd /lib/systemd

SHELL ["/bin/bash", "-c"]



FROM sles15-build-base AS sles15-build-systemd
WORKDIR /work
COPY ./systemd systemd
COPY ./builds/systemd.sh .
RUN ./systemd.sh /work/cache/




FROM sles15-build-base AS sles15-build
WORKDIR /work
COPY . /work

# Copy the pre-compiled Go binaries from the shared build stage
COPY --from=go-build /work/google_cloud_ops_agent_engine /work/google_cloud_ops_agent_engine
COPY --from=go-build /work/cache /work/cache

COPY ./confgenerator/default-config.yaml /work/cache/etc/google-cloud-ops-agent/config.yaml

COPY --from=sles15-build-systemd /work/cache /work/cache

RUN ./pkg/rpm/build.sh

# Copy prebuilt plugin files to cache before packaging the plugin
COPY --from=go-build /work/plugin-cache /work/cache

RUN ./pkg/plugin/build.sh /work/cache sles15


FROM scratch AS sles15
COPY --from=sles15-build /tmp/google-cloud-ops-agent.tgz /google-cloud-ops-agent-sles-15.tgz
COPY --from=sles15-build /google-cloud-ops-agent*.rpm /
COPY --from=sles15-build /google-cloud-ops-agent-plugin*.tar.gz /

# ======================================
# Build Ops Agent for sles-16
# ======================================

FROM opensuse/leap:16.0 AS sles16-build-base

RUN set -x; zypper -n refresh && \
		zypper -n update && \
		zypper -n install systemd rpm-build expect systemd-devel systemd-rpm-macros unzip zip pkgconfig
# Allow fluent-bit to find systemd
RUN ln -fs /usr/lib/systemd /lib/systemd

SHELL ["/bin/bash", "-c"]



FROM sles16-build-base AS sles16-build-systemd
WORKDIR /work
COPY ./systemd systemd
COPY ./builds/systemd.sh .
RUN ./systemd.sh /work/cache/




FROM sles16-build-base AS sles16-build
WORKDIR /work
COPY . /work

# Copy the pre-compiled Go binaries from the shared build stage
COPY --from=go-build /work/google_cloud_ops_agent_engine /work/google_cloud_ops_agent_engine
COPY --from=go-build /work/cache /work/cache

COPY ./confgenerator/default-config.yaml /work/cache/etc/google-cloud-ops-agent/config.yaml

COPY --from=sles16-build-systemd /work/cache /work/cache

RUN ./pkg/rpm/build.sh

# Copy prebuilt plugin files to cache before packaging the plugin
COPY --from=go-build /work/plugin-cache /work/cache

RUN ./pkg/plugin/build.sh /work/cache sles16


FROM scratch AS sles16
COPY --from=sles16-build /tmp/google-cloud-ops-agent.tgz /google-cloud-ops-agent-sles-16.tgz
COPY --from=sles16-build /google-cloud-ops-agent*.rpm /
COPY --from=sles16-build /google-cloud-ops-agent-plugin*.tar.gz /

# ======================================
# Build Ops Agent for ubuntu-jammy
# ======================================

FROM ubuntu:jammy AS jammy-build-base

RUN set -x; apt-get update && \
		DEBIAN_FRONTEND=noninteractive apt-get -y install systemd \
		file libsystemd-dev tzdata \
		devscripts cdbs pkg-config zip

SHELL ["/bin/bash", "-c"]



FROM jammy-build-base AS jammy-build-systemd
WORKDIR /work
COPY ./systemd systemd
COPY ./builds/systemd.sh .
RUN ./systemd.sh /work/cache/




FROM jammy-build-base AS jammy-build
WORKDIR /work
COPY . /work

# Copy the pre-compiled Go binaries from the shared build stage
COPY --from=go-build /work/google_cloud_ops_agent_engine /work/google_cloud_ops_agent_engine
COPY --from=go-build /work/cache /work/cache

COPY ./confgenerator/default-config.yaml /work/cache/etc/google-cloud-ops-agent/config.yaml

COPY --from=jammy-build-systemd /work/cache /work/cache

RUN ./pkg/deb/build.sh

# Copy prebuilt plugin files to cache before packaging the plugin
COPY --from=go-build /work/plugin-cache /work/cache

RUN ./pkg/plugin/build.sh /work/cache jammy


FROM scratch AS jammy
COPY --from=jammy-build /tmp/google-cloud-ops-agent.tgz /google-cloud-ops-agent-ubuntu-jammy.tgz
COPY --from=jammy-build /google-cloud-ops-agent*.deb /
COPY --from=jammy-build /google-cloud-ops-agent-plugin*.tar.gz /

# ======================================
# Build Ops Agent for ubuntu-noble
# ======================================

FROM ubuntu:noble AS noble-build-base

RUN set -x; apt-get update && \
		DEBIAN_FRONTEND=noninteractive apt-get -y install systemd \
		file libsystemd-dev tzdata \
		devscripts cdbs pkg-config zip debhelper

SHELL ["/bin/bash", "-c"]



FROM noble-build-base AS noble-build-systemd
WORKDIR /work
COPY ./systemd systemd
COPY ./builds/systemd.sh .
RUN ./systemd.sh /work/cache/




FROM noble-build-base AS noble-build
WORKDIR /work
COPY . /work

# Copy the pre-compiled Go binaries from the shared build stage
COPY --from=go-build /work/google_cloud_ops_agent_engine /work/google_cloud_ops_agent_engine
COPY --from=go-build /work/cache /work/cache

COPY ./confgenerator/default-config.yaml /work/cache/etc/google-cloud-ops-agent/config.yaml

COPY --from=noble-build-systemd /work/cache /work/cache

RUN ./pkg/deb/build.sh

# Copy prebuilt plugin files to cache before packaging the plugin
COPY --from=go-build /work/plugin-cache /work/cache

RUN ./pkg/plugin/build.sh /work/cache noble


FROM scratch AS noble
COPY --from=noble-build /tmp/google-cloud-ops-agent.tgz /google-cloud-ops-agent-ubuntu-noble.tgz
COPY --from=noble-build /google-cloud-ops-agent*.deb /
COPY --from=noble-build /google-cloud-ops-agent-plugin*.tar.gz /

# ======================================
# Build Ops Agent for ubuntu-questing
# ======================================

FROM ubuntu:questing AS questing-build-base

RUN set -x; apt-get update && \
		DEBIAN_FRONTEND=noninteractive apt-get -y install systemd \
		file systemd-dev debhelper libsystemd-dev tzdata \
		devscripts cdbs pkg-config zip

SHELL ["/bin/bash", "-c"]



FROM questing-build-base AS questing-build-systemd
WORKDIR /work
COPY ./systemd systemd
COPY ./builds/systemd.sh .
RUN ./systemd.sh /work/cache/




FROM questing-build-base AS questing-build
WORKDIR /work
COPY . /work

# Copy the pre-compiled Go binaries from the shared build stage
COPY --from=go-build /work/google_cloud_ops_agent_engine /work/google_cloud_ops_agent_engine
COPY --from=go-build /work/cache /work/cache

COPY ./confgenerator/default-config.yaml /work/cache/etc/google-cloud-ops-agent/config.yaml

COPY --from=questing-build-systemd /work/cache /work/cache

RUN ./pkg/deb/build.sh

# Copy prebuilt plugin files to cache before packaging the plugin
COPY --from=go-build /work/plugin-cache /work/cache

RUN ./pkg/plugin/build.sh /work/cache questing


FROM scratch AS questing
COPY --from=questing-build /tmp/google-cloud-ops-agent.tgz /google-cloud-ops-agent-ubuntu-questing.tgz
COPY --from=questing-build /google-cloud-ops-agent*.deb /
COPY --from=questing-build /google-cloud-ops-agent-plugin*.tar.gz /

FROM scratch
COPY --from=centos8 /* /
COPY --from=rockylinux9 /* /
COPY --from=rockylinux10 /* /
COPY --from=bookworm /* /
COPY --from=bullseye /* /
COPY --from=trixie /* /
COPY --from=sles12 /* /
COPY --from=sles15 /* /
COPY --from=sles16 /* /
COPY --from=jammy /* /
COPY --from=noble /* /
COPY --from=questing /* /