targets:
  bookworm:
    package_extension:
      deb
    architectures:
      x86_64:
        test_distros:
          representative:
          - debian-cloud:debian-12
      aarch64:
        test_distros:
          representative:
          - debian-cloud:debian-12-arm64
  bullseye:
    package_extension:
      deb
    architectures:
      x86_64:
        test_distros:
          representative:
          - debian-cloud:debian-11
          - ml-images:common-gpu-debian-11-py310
      aarch64:
        test_distros:
          representative:
          - debian-cloud:debian-11-arm64
  buster:
    package_extension:
      deb
    architectures:
      x86_64:
        test_distros:
          representative:
          - debian-cloud:debian-10
  centos7:
    package_extension:
      rpm
    repo_name:
      el7
    architectures:
      x86_64:
        test_distros:
          representative:
          - centos-cloud:centos-7
          exhaustive:
          - rhel-cloud:rhel-7
          - rhel-sap-cloud:rhel-7-9-sap-ha
  centos8:
    package_extension:
      rpm
    repo_name:
      el8
    architectures:
      x86_64:
        test_distros:
          representative:
          - rocky-linux-cloud:rocky-linux-8
          exhaustive:
          - rhel-cloud:rhel-8
          - rhel-sap-cloud:rhel-8-2-sap-ha
          - rhel-sap-cloud:rhel-8-4-sap-ha
          - rhel-sap-cloud:rhel-8-6-sap-ha
  focal:
    package_extension:
      deb
    architectures:
      x86_64:
        test_distros:
          representative:
          - ubuntu-os-cloud:ubuntu-2004-lts
          exhaustive:
          - ubuntu-os-cloud:ubuntu-minimal-2004-lts
      aarch64:
        test_distros:
          representative:
          - ubuntu-os-cloud:ubuntu-2004-lts-arm64
          exhaustive:
          - ubuntu-os-cloud:ubuntu-minimal-2004-lts-arm64
  jammy:
    package_extension:
      deb
    architectures:
      x86_64:
        test_distros:
          representative:
          - ubuntu-os-cloud:ubuntu-2204-lts
          exhaustive:
          - ubuntu-os-cloud:ubuntu-minimal-2204-lts
      aarch64:
        test_distros:
          representative:
          - ubuntu-os-cloud:ubuntu-2204-lts-arm64
          exhaustive:
          - ubuntu-os-cloud:ubuntu-minimal-2204-lts-arm64
  mantic:
    package_extension:
      deb
    architectures:
      x86_64:
        test_distros:
          representative:
          - ubuntu-os-cloud:ubuntu-2310-amd64
          exhaustive:
          - ubuntu-os-cloud:ubuntu-minimal-2310-amd64
      aarch64:
        test_distros:
          representative:
          - ubuntu-os-cloud:ubuntu-2310-arm64
          exhaustive:
          - ubuntu-os-cloud:ubuntu-minimal-2310-arm64
  rockylinux9:
    package_extension:
      rpm
    repo_name:
      el9
    architectures:
      x86_64:
        test_distros:
          representative:
          - rocky-linux-cloud:rocky-linux-9
          exhaustive:
          - rhel-cloud:rhel-9
      aarch64:
        test_distros:
          representative:
          - rocky-linux-cloud:rocky-linux-9-arm64
          exhaustive:
          - rhel-cloud:rhel-9-arm64
  sles12:
    package_extension:
      rpm
    architectures:
      x86_64:
        test_distros:
          representative:
          - suse-cloud:sles-12
          exhaustive:
          - suse-sap-cloud:sles-12-sp5-sap
  sles15:
    package_extension:
      rpm
    architectures:
      x86_64:
        test_distros:
          representative:
          - suse-cloud:sles-15
          exhaustive:
          - suse-sap-cloud:sles-15-sp2-sap
          - suse-sap-cloud:sles-15-sp5-sap
          - opensuse-cloud:opensuse-leap
          - opensuse-cloud=opensuse-leap-15-4-v20231208-x86-64
      aarch64:
        test_distros:
          representative:
          - suse-cloud:sles-15-arm64
          exhaustive:
          - opensuse-cloud:opensuse-leap-arm64
  windows:
    package_extension:
      goo
    architectures:
      x86_64:
        test_distros:
          representative:
          - windows-cloud:windows-2016-core
          - windows-sql-cloud:sql-std-2019-win-2019
          - windows-cloud:windows-2022
          exhaustive:
          - windows-cloud:windows-2016
          - windows-cloud:windows-2019
          - windows-cloud:windows-2019-core
          - windows-cloud:windows-2022-core
