targets:
  bookworm:
    package_extension:
      deb
    architectures:
      x86_64:
        test_distros:
          representative:
          - debian-12
      aarch64:
        test_distros:
          representative:
          - debian-12-arm64
  bullseye:
    package_extension:
      deb
    architectures:
      x86_64:
        test_distros:
          representative:
          - debian-11
      aarch64:
        test_distros:
          representative:
          - debian-11-arm64
  buster:
    package_extension:
      deb
    architectures:
      x86_64:
        test_distros:
          representative:
          - debian-10
  centos7:
    package_extension:
      rpm
    repo_name:
      el7
    architectures:
      x86_64:
        test_distros:
          representative:
          - centos-7
          exhaustive:
          - rhel-7
          - rhel-7-9-sap-ha
  focal:
    package_extension:
      deb
    architectures:
      x86_64:
        test_distros:
          representative:
          - ubuntu-minimal-2004-lts
          exhaustive:
          - ubuntu-2004-lts
      aarch64:
        test_distros:
          representative:
          - ubuntu-minimal-2004-lts-arm64
          exhaustive:
          - ubuntu-2004-lts-arm64
  jammy:
    package_extension:
      deb
    architectures:
      x86_64:
        test_distros:
          representative:
          - ubuntu-minimal-2204-lts
          exhaustive:
          - ubuntu-2204-lts
      aarch64:
        test_distros:
          representative:
          - ubuntu-minimal-2204-lts-arm64
          exhaustive:
          - ubuntu-2204-lts-arm64
  mantic:
    package_extension:
      deb
    architectures:
      x86_64:
        test_distros:
          representative:
          - ubuntu-minimal-2310-amd64
          exhaustive:
          - ubuntu-2310-amd64
      aarch64:
        test_distros:
          representative:
          - ubuntu-minimal-2310-arm64
          exhaustive:
          - ubuntu-2310-arm64
  rockylinux8:
    package_extension:
      rpm
    repo_name:
      el8
    architectures:
      x86_64:
        test_distros:
          representative:
          - rocky-linux-8
          exhaustive:
          - rhel-8
          - rhel-8-2-sap-ha
          - rhel-8-4-sap-ha
          - rhel-8-6-sap-ha
  rockylinux9:
    package_extension:
      rpm
    repo_name:
      el9
    architectures:
      x86_64:
        test_distros:
          representative:
          - rocky-linux-9
          exhaustive:
          - rhel-9
      aarch64:
        test_distros:
          representative:
          - rocky-linux-9-arm64
          exhaustive:
          - rhel-9-arm64
  sles12:
    package_extension:
      rpm
    architectures:
      x86_64:
        test_distros:
          representative:
          - sles-12
          exhaustive:
          - sles-12-sp5-sap
  sles15:
    package_extension:
      rpm
    architectures:
      x86_64:
        test_distros:
          representative:
          - sles-15
          exhaustive:
          - sles-15-sp2-sap
          - sles-15-sp5-sap
          - opensuse-leap
          - opensuse-leap-15-4
      aarch64:
        test_distros:
          representative:
          - sles-15-arm64
          exhaustive:
          - opensuse-leap-arm64
  windows:
    package_extension:
      goo
    architectures:
      x86_64:
        test_distros:
          representative:
          - windows-2016-core
          - sql-std-2019-win-2019
          - windows-2022
          exhaustive:
          - windows-2016
          - windows-2019
          - windows-2019-core
          - windows-2022-core
