targets:
  oracular:
    package_extension:
      deb
    architectures:
      x86_64:
        test_distros:
          representative:
          - ubuntu-os-cloud:ubuntu-2410-amd64
          exhaustive:
          - ubuntu-os-cloud:ubuntu-minimal-2410-amd64
      aarch64:
        test_distros:
          representative:
          - ubuntu-os-cloud:ubuntu-2410-arm64
          exhaustive:
          - ubuntu-os-cloud:ubuntu-minimal-2410-arm64
  bookworm:
    package_extension:
      deb
    architectures:
      x86_64:
        test_distros:
          representative:
          - debian-cloud:debian-12
      aarch64:
        test_distros:
          representative:
          - debian-cloud:debian-12-arm64
  bullseye:
    package_extension:
      deb
    architectures:
      x86_64:
        test_distros:
          representative:
          - debian-cloud:debian-11
          - ml-images:common-gpu-debian-11-py310
  centos8:
    package_extension:
      rpm
    repo_name:
      el8
    architectures:
      x86_64:
        test_distros:
          representative:
          - rocky-linux-cloud:rocky-linux-8
          exhaustive:
          - rhel-cloud:rhel-8
          - rhel-sap-cloud:rhel-8-4-sap-ha
          - rhel-sap-cloud:rhel-8-6-sap-ha
          - rhel-sap-cloud:rhel-8-8-sap-ha
          - rocky-linux-cloud:rocky-linux-8-optimized-gcp
      aarch64:
        test_distros:
          representative:
          - rocky-linux-cloud:rocky-linux-8-optimized-gcp-arm64
  focal:
    package_extension:
      deb
    architectures:
      x86_64:
        soak_distro:
          ubuntu-os-cloud:ubuntu-2004-lts
        test_distros:
          representative:
          - ubuntu-os-cloud:ubuntu-2004-lts
          exhaustive:
          - ubuntu-os-cloud:ubuntu-minimal-2004-lts
      aarch64:
        test_distros:
          representative:
          - ubuntu-os-cloud:ubuntu-2004-lts-arm64
          exhaustive:
          - ubuntu-os-cloud:ubuntu-minimal-2004-lts-arm64
  jammy:
    package_extension:
      deb
    architectures:
      x86_64:
        test_distros:
          representative:
          - ubuntu-os-cloud:ubuntu-2204-lts
          exhaustive:
          - ubuntu-os-cloud:ubuntu-minimal-2204-lts
      aarch64:
        test_distros:
          representative:
          - ubuntu-os-cloud:ubuntu-2204-lts-arm64
          exhaustive:
          - ubuntu-os-cloud:ubuntu-minimal-2204-lts-arm64
  noble:
    package_extension:
      deb
    architectures:
      x86_64:
        test_distros:
          representative:
          - ubuntu-os-cloud:ubuntu-2404-lts-amd64
          exhaustive:
          - ubuntu-os-cloud:ubuntu-minimal-2404-lts-amd64
      aarch64:
        test_distros:
          representative:
          - ubuntu-os-cloud:ubuntu-2404-lts-arm64
          exhaustive:
          - ubuntu-os-cloud:ubuntu-minimal-2404-lts-arm64
  rockylinux9:
    package_extension:
      rpm
    repo_name:
      el9
    architectures:
      x86_64:
        test_distros:
          representative:
          - rocky-linux-cloud:rocky-linux-9
          exhaustive:
          - rhel-cloud:rhel-9
          - rocky-linux-cloud:rocky-linux-9-optimized-gcp
      aarch64:
        test_distros:
          representative:
          - rocky-linux-cloud:rocky-linux-9-arm64
          exhaustive:
          - rhel-cloud:rhel-9-arm64
          - rocky-linux-cloud:rocky-linux-9-optimized-gcp-arm64
  sles12:
    package_extension:
      rpm
    architectures:
      x86_64:
        test_distros:
          representative:
          - suse-cloud:sles-12
          exhaustive:
          - suse-sap-cloud:sles-12-sp5-sap
  sles15:
    package_extension:
      rpm
    architectures:
      x86_64:
        test_distros:
          representative:
          - suse-cloud:sles-15
          exhaustive:
          - suse-sap-cloud:sles-15-sp6-sap
          - opensuse-cloud:opensuse-leap
          - opensuse-cloud=opensuse-leap-15-5-v20240516-x86-64
          - opensuse-cloud=opensuse-leap-15-6-v20240612-x86-64
      aarch64:
        test_distros:
          representative:
          - suse-cloud:sles-15-arm64
          exhaustive:
          - opensuse-cloud:opensuse-leap-arm64
          - opensuse-cloud=opensuse-leap-15-5-v20240516-arm64
          - opensuse-cloud=opensuse-leap-15-6-v20240612-arm64
  windows:
    package_extension:
      goo
    architectures:
      x86_64:
        soak_distro:
          windows-cloud:windows-2022
        test_distros:
          representative:
          - windows-cloud:windows-2016-core
          - windows-cloud:windows-2022
          - windows-sql-cloud:sql-std-2019-win-2019
          - windows-sql-cloud:sql-std-2022-win-2022  
          exhaustive:
          - windows-cloud:windows-2016
          - windows-cloud:windows-2019
          - windows-cloud:windows-2019-core
          - windows-cloud:windows-2022-core
