#!/bin/bash

set -e

sudo apt-get update
sudo apt-get install -y gnupg wget curl

## Following instructions from https://docs.couchbase.com/server/current/install/ubuntu-debian-install.html

curl -O https://packages.couchbase.com/releases/couchbase-release/couchbase-release-1.0-amd64.deb
sudo dpkg -i ./couchbase-release-1.0-amd64.deb

sudo apt-get update
sudo apt-get install -y couchbase-server-community=7.1.0-2556-1

/opt/couchbase/bin/couchbase-cli cluster-init -c 127.0.0.1 --cluster-username admin --cluster-password password \
  --cluster-name otelc --cluster-ramsize 256 --cluster-index-ramsize 256 --services data,index,query,fts \
  --index-storage-setting default

/opt/couchbase/bin/couchbase-cli bucket-create -c 127.0.0.1 --username otelu --password otelpassword --bucket-type couchbase --bucket-ramsize 256 --bucket otelb