// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"os"
	"testing"
)

func TestDockerfileMatches(t *testing.T) {
	gotDockerfile, err := os.ReadFile(getDockerfilePath())
	if os.IsNotExist(err) {
		t.Skip("Dockerfile not found")
	} else if err != nil {
		t.Error(err)
	}
	expectedDockerfile, err := getDockerfile()
	if err != nil {
		t.Error(err)
	}
	if expectedDockerfile != string(gotDockerfile) {
		t.Fatalf("Dockerfile was not generated by ./dockerfiles/compile. Please run `go run ./dockerfiles`")
	}
}
