#!/bin/bash

sudo yum install -y gnupg wget curl

curl -O https://packages.couchbase.com/releases/couchbase-release/couchbase-release-1.0-x86_64.rpm
sudo yum install -y ./couchbase-release-1.0-x86_64.rpm

sudo yum install -y couchbase-server-community-7.1.0-2556

sleep 20

/opt/couchbase/bin/couchbase-cli cluster-init -c 127.0.0.1 --cluster-username admin --cluster-password password \
  --cluster-name otelc --cluster-ramsize 256 --cluster-index-ramsize 256 --services data,index,query,fts \
  --index-storage-setting default

/opt/couchbase/bin/couchbase-cli bucket-create -c 127.0.0.1 --username admin --password password --bucket-type couchbase --bucket-ramsize 256 --bucket otelb