#!/bin/bash

sudo yum install -y gnupg wget curl

curl -O https://packages.couchbase.com/releases/couchbase-release/couchbase-release-1.0-x86_64.rpm
sudo yum install -y ./couchbase-release-1.0-x86_64.rpm

sudo run yum --enablerepo=couchbase-server-community clean metadata

sudo yum install -y couchbase-server-community

timeout 60s bash <<EOF
wait_for_couchbase() {
    until curl localhost:8091 > /dev/null 2>&1
    do
        echo "Waiting for couchbase to start. . ."
        sleep "1"
    done
}

wait_for_couchbase

sleep 5

echo "couchbase started"
EOF

/opt/couchbase/bin/couchbase-cli cluster-init -c 127.0.0.1 --cluster-username admin --cluster-password password \
  --cluster-name otelc --cluster-ramsize 256 --cluster-index-ramsize 256 --services data,index,query,fts \
  --index-storage-setting default

/opt/couchbase/bin/couchbase-cli bucket-create -c 127.0.0.1 --username admin --password password --bucket-type couchbase --bucket-ramsize 256 --bucket otelb