#!/bin/sh
set -e

# Upgrade from <2.0 needs to stop the .target
# The .target's state will be copied to the .service in postinst
deb-systemd-invoke stop 'google-cloud-ops-agent.target' >/dev/null 2>&1 || true

# If the user ran `systemctl disable google-cloud-ops-agent.target`, sync
# that state into the dsh state file so the postinst can avoid enabling
# google-cloud-ops-agent.service
if deb-systemd-helper --quiet debian-installed google-cloud-ops-agent.target \
  && deb-systemd-helper --quiet was-enabled google-cloud-ops-agent.target 2>/dev/null \
  && ! deb-systemd-helper --quiet is-enabled google-cloud-ops-agent.target 2>/dev/null; then
  deb-systemd-helper disable google-cloud-ops-agent.target
fi

#DEBHELPER#
