// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/pdata/pcommon"
)

// ResourceBuilder is a helper struct to build resources predefined in metadata.yaml.
// The ResourceBuilder is not thread-safe and must not to be used in multiple goroutines.
type ResourceBuilder struct {
	config ResourceAttributesConfig
	res    pcommon.Resource
}

// NewResourceBuilder creates a new ResourceBuilder. This method should be called on the start of the application.
func NewResourceBuilder(rac ResourceAttributesConfig) *ResourceBuilder {
	return &ResourceBuilder{
		config: rac,
		res:    pcommon.NewResource(),
	}
}

// SetGpuModel sets provided value as "gpu.model" attribute.
func (rb *ResourceBuilder) SetGpuModel(val string) {
	if rb.config.GpuModel.Enabled {
		rb.res.Attributes().PutStr("gpu.model", val)
	}
}

// SetGpuNumber sets provided value as "gpu.number" attribute.
func (rb *ResourceBuilder) SetGpuNumber(val string) {
	if rb.config.GpuNumber.Enabled {
		rb.res.Attributes().PutStr("gpu.number", val)
	}
}

// SetGpuUUID sets provided value as "gpu.uuid" attribute.
func (rb *ResourceBuilder) SetGpuUUID(val string) {
	if rb.config.GpuUUID.Enabled {
		rb.res.Attributes().PutStr("gpu.uuid", val)
	}
}

// Emit returns the built resource and resets the internal builder state.
func (rb *ResourceBuilder) Emit() pcommon.Resource {
	r := rb.res
	rb.res = pcommon.NewResource()
	return r
}
