// Code generated by "go.opentelemetry.io/collector/cmd/builder". DO NOT EDIT.

// Program otelopscol is an OpenTelemetry Collector binary.
package main

import (
	"os"

	googlesecretmanagerprovider "github.com/open-telemetry/opentelemetry-collector-contrib/confmap/provider/googlesecretmanagerprovider"
	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/collector/confmap"
	envprovider "go.opentelemetry.io/collector/confmap/provider/envprovider"
	fileprovider "go.opentelemetry.io/collector/confmap/provider/fileprovider"
	"go.opentelemetry.io/collector/otelcol"
)

func main() {
	info := component.BuildInfo{
		Command:     "otelopscol",
		Description: "OpenTelemetry Collector binary used by the Ops Agent",
		Version:     "v0.151.0",
	}

	set := otelcol.CollectorSettings{
		BuildInfo: info,
		Factories: components,
		ConfigProviderSettings: otelcol.ConfigProviderSettings{
			ResolverSettings: confmap.ResolverSettings{
				ProviderFactories: []confmap.ProviderFactory{
					googlesecretmanagerprovider.NewFactory(),
					envprovider.NewFactory(),
					fileprovider.NewFactory(),
				},
			},
		},
		ProviderModules: map[string]string{
			googlesecretmanagerprovider.NewFactory().Create(confmap.ProviderSettings{}).Scheme(): "github.com/open-telemetry/opentelemetry-collector-contrib/confmap/provider/googlesecretmanagerprovider v0.151.0",
			envprovider.NewFactory().Create(confmap.ProviderSettings{}).Scheme():                 "go.opentelemetry.io/collector/confmap/provider/envprovider v1.57.0",
			fileprovider.NewFactory().Create(confmap.ProviderSettings{}).Scheme():                "go.opentelemetry.io/collector/confmap/provider/fileprovider v1.57.0",
		},
		ConverterModules: []string{},
	}

	if err := run(set); err != nil {
		// The error message is logged by cobra, so we intentionally
		// avoid logging it again here to prevent duplicate output.
		os.Exit(1)
	}
}

func runInteractive(params otelcol.CollectorSettings) error {
	cmd := otelcol.NewCommand(params)
	if err := cmd.Execute(); err != nil {
		return err
	}

	return nil
}
